apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orders-postgres.fullname" . }}
  labels:
    {{- include "orders-postgres.labels" . | nindent 4 }}
data:
  POSTGRES_USER: "{{ .Values.global.postgres.username }}"
  POSTGRES_DB: "{{ .Values.global.postgres.dbname }}"
