apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "orders-postgres.labels" . | nindent 4 }}
  name: {{ include "orders-postgres.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "orders-postgres.selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      labels:
        {{- include "orders-postgres.labels" . | nindent 8 }}
    spec:
      volumes:
        - name: postgres-data
          emptyDir: {}
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: postgres
          ports:
            - containerPort: {{ include "orders-postgres.port" . }}
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "orders-postgres.fullname" . }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "orders-postgres.fullname" . }}
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "orders-postgres.fullname" . }}
                  key: POSTGRES_DB
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
          resources: {}
