apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orders-postgres.fullname" . }}
  labels:
    {{- include "orders-postgres.labels" . | nindent 4 }}
data:
  POSTGRES_PASSWORD: {{ required "global.postgres.password est obligatoire, fournis-le via --set ou -f" .Values.global.postgres.password | b64enc }}