apiVersion: v1
kind: Service
metadata:
  name: {{ include "orders-postgres.fullname" . }}
  labels:
    {{- include "orders-postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ include "orders-postgres.port" . }}
      targetPort: {{ include "orders-postgres.port" . }}
      protocol: TCP
  selector:
    {{- include "orders-postgres.selectorLabels" . | nindent 4 }}
