apiVersion: v2
name: retail-store-chart
description: Umbrella chart for the retail store sample app
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: checkout-redis
    version: "0.1.0"
    condition: checkout-redis.enabled
  - name: checkout
    version: "0.1.0"
    condition: checkout.enabled
  - name: orders-postgres
    version: "0.1.0"
    condition: orders-postgres.enabled
  - name: orders
    version: "0.1.0"
    condition: orders.enabled
  - name: cart-dynamodb
    version: "0.1.0"
    condition: cart-dynamodb.enabled
  - name: cart
    version: "0.1.0"
    condition: cart.enabled
  - name: catalog-mysql
    version: "0.1.0"
    condition: catalog-mysql.enabled
  - name: catalog
    version: "0.1.0"
    condition: catalog.enabled
