global:
  postgres:
    provider: "postgres"
    secretArn: "arn:aws:secretsmanager:eu-north-1:745838912158:secret:rds!db-202eac98-78c2-4ebd-871b-952fed957d77-MhHe3i"
  mysql:
    provider: "mysql"
    secretArn: "arn:aws:secretsmanager:eu-north-1:745838912158:secret:rds!db-dfa43ae9-5b46-4e97-bebf-edbcea18cfd0-xo9s0W"
  redis:
    provider: "redis"
  env: "dev"
  ecrRegistry: "745838912158.dkr.ecr.eu-north-1.amazonaws.com/retail-store"
checkout-redis:
  enabled: false
checkout:
  enabled: true
orders-postgres:
  enabled: false
orders:
  enabled: true
cart-dynamodb:
  enabled: false
cart:
  enabled: true
catalog-mysql:
  enabled: false
catalog:
  enabled: true
ui:
  enabled: true
