apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "catalog-mysql.labels" . | nindent 4 }}
  name: {{ include "catalog-mysql.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "catalog-mysql.selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      labels:
        {{- include "catalog-mysql.labels" . | nindent 8 }}
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: mysql
          ports:
            - containerPort: {{ include "catalog-mysql.port" . }}
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "catalog-mysql.fullname" . }}
                  key: MARIADB_ROOT_PASSWORD
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "catalog-mysql.fullname" . }}
                  key: MARIADB_PASSWORD
            - name: MARIADB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "catalog-mysql.fullname" . }}
                  key: MARIADB_DATABASE
            - name: MARIADB_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "catalog-mysql.fullname" . }}
                  key: MARIADB_USER
          livenessProbe:
            exec:
              command:
                - healthcheck.sh
                - --connect
                - --innodb_initialized
          readinessProbe:
            exec:
              command:
                - healthcheck.sh
                - --connect
                - --innodb_initialized
          resources: {}
