apiVersion: v1
kind: Secret
metadata:
  name: {{ include "catalog-mysql.fullname" . }}
  labels:
    {{- include "catalog-mysql.labels" . | nindent 4 }}
data:
  MARIADB_ROOT_PASSWORD: {{ required "global.mysql.rootpassword est obligatoire, fournis-le via --set ou -f" .Values.global.mysql.rootpassword | b64enc }}
  MARIADB_PASSWORD: {{ required "global.mysql.password est obligatoire, fournis-le via --set ou -f" .Values.global.mysql.password | b64enc }}