apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orders.fullname" . }}
  labels:
    {{- include "orders.labels" . | nindent 4 }}
data:
  RETAIL_ORDERS_PERSISTENCE_PROVIDER: {{ .Values.global.postgres.provider }}
  RETAIL_ORDERS_PERSISTENCE_ENDPOINT: "{{ .Values.global.postgres.host }}:{{ .Values.global.postgres.port }}"
