apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "checkout-redis.labels" . | nindent 4 }}
  name: {{ include "checkout-redis.fullname" . }}
spec:
  ports:
    - port: {{ include "checkout-redis.port" . }}
      protocol: TCP
      targetPort: {{ include "checkout-redis.port" . }}
  selector:
    {{- include "checkout-redis.selectorLabels" . | nindent 4 }}
  type: ClusterIP
