apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "checkout.fullname" . }}
  labels:
    {{- include "checkout.labels" . | nindent 4 }}
data:
  RETAIL_CHECKOUT_PERSISTENCE_PROVIDER: {{ .Values.configMap.provider }}
  RETAIL_CHECKOUT_PERSISTENCE_REDIS_URL: "redis://{{ .Values.global.redis.host }}:{{ .Values.global.redis.port }}"
