apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: checkout-connection
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-parameter-store
  target:
    name: {{ include "checkout.fullname" . }}
    creationPolicy: Owner
  data:
    - secretKey: RETAIL_CHECKOUT_PERSISTENCE_REDIS_URL
      remoteRef:
        key: /retail-store/{{ .Values.global.env }}/checkout/redis-url