apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cart.fullname" . }}
  labels:
    {{- include "cart.labels" . | nindent 4 }}
data:
  AWS_ACCESS_KEY_ID: {{ required "global.aws.accessKey est obligatoire, fournis-le via --set ou -f" .Values.global.aws.accessKey | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ required "global.aws.secretKey est obligatoire, fournis-le via --set ou -f" .Values.global.aws.secretKey | b64enc }}