apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "catalog.fullname" . }}
  labels:
    {{- include "catalog.labels" . | nindent 4 }}
data:
  RETAIL_CATALOG_PERSISTENCE_PROVIDER: {{ .Values.global.mysql.provider }}
  RETAIL_CATALOG_PERSISTENCE_ENDPOINT: "{{ .Values.global.mysql.host }}:{{ .Values.global.mysql.port }}"
