apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "catalog.labels" . | nindent 4 }}
  name: {{ include "catalog.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "catalog.selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      labels:
        {{- include "catalog.labels" . | nindent 8 }}
    spec:
      containers:
      - image: "{{ .Values.global.ecrRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: catalog
        ports:
          - containerPort: {{ .Values.service.targetPort }}
        env:
          - name: RETAIL_CATALOG_PERSISTENCE_PROVIDER
            value: {{ .Values.global.mysql.provider }}
          - name: RETAIL_CATALOG_PERSISTENCE_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: {{ include "catalog.fullname" . }}
                key: RETAIL_CATALOG_PERSISTENCE_ENDPOINT
          - name: RETAIL_CATALOG_PERSISTENCE_DB_NAME
            valueFrom:
              secretKeyRef:
                name: {{ include "catalog.fullname" . }}
                key: RETAIL_CATALOG_PERSISTENCE_DB_NAME
          - name: RETAIL_CATALOG_PERSISTENCE_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "catalog.fullname" . }}
                key: RETAIL_CATALOG_PERSISTENCE_USER
          - name: RETAIL_CATALOG_PERSISTENCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "catalog.fullname" . }}
                key: RETAIL_CATALOG_PERSISTENCE_PASSWORD
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.httpGet.path }}
            port: {{ .Values.livenessProbe.httpGet.port }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.httpGet.path }}
            port: {{ .Values.readinessProbe.httpGet.port }}
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
status: {}
