apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: catalog-connection
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-parameter-store
  target:
    name: {{ include "catalog.fullname" . }}
    creationPolicy: Orphan
  data:
    - secretKey: RETAIL_CATALOG_PERSISTENCE_ENDPOINT
      remoteRef:
        key: /retail-store/{{ .Values.global.env }}/catalog/host
    - secretKey: RETAIL_CATALOG_PERSISTENCE_DB_NAME
      remoteRef:
        key: /retail-store/{{ .Values.global.env }}/catalog/dbname
    - secretKey: RETAIL_CATALOG_PERSISTENCE_USER
      remoteRef:
        key: /retail-store/{{ .Values.global.env }}/catalog/username
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: catalog-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: {{ include "catalog.fullname" . }}
    creationPolicy: Merge
  data:
    - secretKey: RETAIL_CATALOG_PERSISTENCE_PASSWORD
      remoteRef:
        key: "{{ .Values.global.mysql.secretArn }}"
        property: password